#release configuration
#Fri Apr 11 12:13:39 WEST 2025
projectVersionPolicyId=default
project.scm.com.bezkoder\:api-sp3dk17.connection=scm\:git\:https\://https\://github.com/git1978/spring-boot-swagger-3-example.git
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.com.bezkoder\:api-sp3dk17.url=https\://github.com/git1978/spring-boot-swagger-3-example.git
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.com.bezkoder\:api-sp3dk17.tag=HEAD
pinExternals=false
completedPhase=check-poms
scm.url=scm\:git\:https\://github.com/git1978/spring-boot-swagger-3-exampleg.it
scm.developmentCommitComment=@{prefix} prepare for next development iteration
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.scm.com.bezkoder\:api-sp3dk17.developerConnection=scm\:git\:https\://github.com/git1978/spring-boot-swagger-3-exampleg.it
scm.tag=v1.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
