### AZURE
springdoc.swagger-ui.path=/bezkoder-documentation
springdoc.api-docs.path=/bezkoder-api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true


bezkoder.openapi.dev-url=https://spring-boot-swagger-3-example-cge4c4bhfwfagkcw.canadacentral-01.azurewebsites.net/
bezkoder.openapi.prod-url=https://bezkoder-api.com
springdoc.path.file=https://storegdt.blob.core.windows.net/container-json


### LOCAL
### springdoc.swagger-ui.path=/bezkoder-documentation
### springdoc.api-docs.path=/bezkoder-api-docs
### springdoc.swagger-ui.tryItOutEnabled=true
### springdoc.swagger-ui.filter=true

### bezkoder.openapi.dev-url=http://localhost:8080
### bezkoder.openapi.prod-url=https://bezkoder-api.com
### springdoc.path.file=/Users/younessabach/Documents/dev/workspaceJava/spring-boot-swagger-3-example





### azure configuration ###
azure.storage.account.name=storegdt
azure.storage.account.key=365e9d1df3db4a0bb364428358e14ab5
azure.storage.container.name=container-json
azure.storage.blob.name=products.json