#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false
#springdoc.packages-to-scan=com.bezkoder.spring.swagger.controller
springdoc.swagger-ui.path=/bezkoder-documentation
springdoc.api-docs.path=/bezkoder-api-docs
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

#bezkoder.openapi.dev-url=https://spring-boot-swagger-3-example-cge4c4bhfwfagkcw.canadacentral-01.azurewebsites.net/
bezkoder.openapi.prod-url=https://bezkoder-api.com
bezkoder.openapi.dev-url=http://localhost:8080
#bezkoder.openapi.prod-url=https://bezkoder-api.com
springdoc.path.file=/Users/younessabach/Documents/dev/workspaceJava/spring-boot-swagger-3-example
#springdoc.path.file=https://storegdt.blob.core.windows.net/container-json

