name: Build and deploy JAR app to Azure Web App - spring-boot-swagger-3-example

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ github.workspace }}/target/*.jar
          compression-level: 0  # Optionnel : améliore la vitesse d'upload

  deploy:
    runs-on: windows-latest
    needs: build
    environment: Production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app  # Assure que le fichier est bien téléchargé dans un dossier spécifique

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spring-boot-swagger-3-example'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_120B8895E0DC48E388443B1C813E8CB3 }}
          package: java-app/*.jar
